### ISSUE TITLE
Greetings

### ISSUE THREAD

**Issue by moose4lord** [debsahu/NeoAnimationFX#1]
Hi Deb, thanks for inviting me to collaborate on your GitHub project. I had been looking at integrating NeoPixelBus into WS2812FX, but it was becoming very cumbersome. I couldn't figure out an elegant way of inheriting from both Adafruit_Neopixel and NeoPixelBus classes, so it's been put on the back burner for a while. What you have looks like a good start, although I was sad to see you don't support segments. Maybe that will be in your v2.0 release :)

I'm sorry I don't really have time to devote to NeoAnimationFX. Too many other irons in the fire. But if you really get stuck, reach out to me and I'll try to help. 

Best of luck,
Keith

P.S. One thing I noticed while I was playing with your catalog_animations example is you're not always using the _maxled variable as it should be. It is set to (numPixels -1), but sometimes it is used as if it were set to numPixels. In your mode_color_wipe_random() function, for instance, you have this:

```c++
  uint16_t mode_color_wipe_random(void) {
    if(counter_mode_step % _maxled == 0) {
      aux_param = get_random_wheel_index(aux_param);
    }
    uint32_t color = color_wheel(aux_param);
    return color_wipe(_color, color, false) * 2;
  }
```

but this produces incorrect lighting at the end of the strip. It should be this:

```c++
  uint16_t mode_color_wipe_random(void) {
    if(counter_mode_step % (_maxled + 1) == 0) {
      aux_param = get_random_wheel_index(aux_param);
    }
    uint32_t color = color_wheel(aux_param);
    return color_wipe(color, color, false) * 2;
  }
```

**Comment by moose4lord** [comment]
I didn't see a meteor rain effect. Is that something new you added?

**Comment by debsahu** [comment]
lol forgot to add mode. its mode #57

**Comment by debsahu** [comment]
Segments are now supported, just like WS2812FX. All modes are now identical to WS2812FX + added "meteor rain".
